Document: flask-app-deb
Title: Debian flask-app-deb Manual
Author: <insert document author here>
Abstract: This manual describes what flask-app-deb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flask-app-deb/flask-app-deb.sgml.gz

Format: postscript
Files: /usr/share/doc/flask-app-deb/flask-app-deb.ps.gz

Format: text
Files: /usr/share/doc/flask-app-deb/flask-app-deb.text.gz

Format: HTML
Index: /usr/share/doc/flask-app-deb/html/index.html
Files: /usr/share/doc/flask-app-deb/html/*.html
