language : python 3.9

#schedule cron job in every month

cron : 
  -  "0 0 1 * *"

#install dependencies

install : 
  -  pip install -r requirements.txt

#build package
    python build_package.py

#deploy package to test to build/test folder

deploy : 
    provider : releases
    api_key : $GITHUB_TOKEN
    file : dist/test/*.tar.gz
    skip_cleanup : true
    on : 
      tags : true
#deploy to build folder

deploy : 
  provider :  releases
  api_key :  $GITHUB_TOKEN
  file :  dist/*.tar.gz
  skip_cleanup :  true
  on : 
    tags :  true


